import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    paddingTop: 30,
    paddingRight: 30,
    paddingBottom: 30,
    paddingLeft: 30,
    fontSize: 10,
    lineHeight: 1.4,
  },
  title: {
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 6,
  },
  subtitle: {
    marginBottom: 2,
  },
  section: {
    marginTop: 12,
  },
  table: {
    display: "table",
    width: "100%",
    borderWidth: 1,
    borderColor: "#333",
    marginTop: 8,
  },
  tableRow: {
    flexDirection: "row",
  },
  tableHeader: {
    backgroundColor: "#efefef",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  cell: {
    paddingTop: 5,
    paddingRight: 4,
    paddingBottom: 5,
    paddingLeft: 4,
    borderRightWidth: 1,
    borderRightColor: "#333",
  },
  cellLast: {
    borderRightWidth: 0,
  },
  rowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  strong: {
    fontWeight: 700,
  },
});

const safeText = (value) => {
  if (value === null || value === undefined || value === "") {
    return "-";
  }

  return String(value);
};

const lkrFormatter = new Intl.NumberFormat("en-LK", {
  style: "currency",
  currency: "LKR",
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

const formatCurrency = (value) => {
  const amount = Number(value);
  if (!Number.isFinite(amount)) {
    return "LKR 0.00";
  }

  return lkrFormatter.format(amount);
};

export function TecReportPdf({ job, rows, generatedBy, generatedAt }) {
  const list = Array.isArray(rows) ? rows : [];

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>TEC Recommendation Report</Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Job Number: </Text>
          {safeText(job?.job_number || job?.jobNumber || job?.id)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Procurement Method: </Text>
          {safeText(job?.procurement_method || job?.procurementMethod)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Generated By: </Text>
          {safeText(generatedBy)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Generated At: </Text>
          {safeText(generatedAt)}
        </Text>

        <View style={styles.section}>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={[styles.cell, { width: "20%" }]}>Supplier</Text>
              <Text style={[styles.cell, { width: "20%" }]}>Item</Text>
              <Text style={[styles.cell, { width: "7%" }]}>Qty</Text>
              <Text style={[styles.cell, { width: "13%" }]}>Unit Price</Text>
              <Text style={[styles.cell, { width: "14%" }]}>Decision</Text>
              <Text style={[styles.cell, { width: "6%" }]}>Rec.</Text>
              <Text style={[styles.cell, styles.cellLast, { width: "20%" }]}>Remarks</Text>
            </View>

            {list.length === 0 ? (
              <View style={styles.tableRow}>
                <Text style={[styles.cell, styles.cellLast, { width: "100%" }]}>No TEC entries available.</Text>
              </View>
            ) : (
              list.map((row, index) => (
                <View
                  key={`${row?.supplierId || row?.supplier_id || "supplier"}-${index}`}
                  style={[styles.tableRow, styles.rowBorder]}
                >
                  <Text style={[styles.cell, { width: "20%" }]}>{safeText(row?.supplierName || row?.supplier_name)}</Text>
                  <Text style={[styles.cell, { width: "20%" }]}>{safeText(row?.itemName || row?.item_name)}</Text>
                  <Text style={[styles.cell, { width: "7%" }]}>{safeText(row?.quantity)}</Text>
                  <Text style={[styles.cell, { width: "13%" }]}>{formatCurrency(row?.unitPrice ?? row?.unit_price)}</Text>
                  <Text style={[styles.cell, { width: "14%" }]}>{safeText(row?.decisionStatus || row?.decision_status)}</Text>
                  <Text style={[styles.cell, { width: "6%" }]}>{row?.isRecommended || row?.is_recommended ? "Yes" : "No"}</Text>
                  <Text style={[styles.cell, styles.cellLast, { width: "20%" }]}>{safeText(row?.remarks)}</Text>
                </View>
              ))
            )}
          </View>
        </View>
      </Page>
    </Document>
  );
}

export function CommitteeReportPdf({ job, report, generatedBy, generatedAt }) {
  const suppliers = Array.isArray(report?.reportData?.suppliers)
    ? report.reportData.suppliers
    : [];

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>Committee Report</Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Job Number: </Text>
          {safeText(job?.job_number || job?.jobNumber || job?.id)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Procurement Method: </Text>
          {safeText(job?.procurement_method || job?.procurementMethod)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Committee Type: </Text>
          {safeText(report?.committee_type)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Total Amount: </Text>
          {formatCurrency(report?.total_amount)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Generated By: </Text>
          {safeText(generatedBy)}
        </Text>
        <Text style={styles.subtitle}>
          <Text style={styles.strong}>Generated At: </Text>
          {safeText(generatedAt)}
        </Text>

        <View style={styles.section}>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={[styles.cell, { width: "35%" }]}>Supplier</Text>
              <Text style={[styles.cell, { width: "20%" }]}>Items</Text>
              <Text style={[styles.cell, styles.cellLast, { width: "45%" }]}>Total Amount</Text>
            </View>

            {suppliers.length === 0 ? (
              <View style={styles.tableRow}>
                <Text style={[styles.cell, styles.cellLast, { width: "100%" }]}>No committee summary available.</Text>
              </View>
            ) : (
              suppliers.map((supplier, index) => (
                <View
                  key={`${supplier?.supplierId || "supplier"}-${index}`}
                  style={[styles.tableRow, styles.rowBorder]}
                >
                  <Text style={[styles.cell, { width: "35%" }]}>{safeText(supplier?.supplierName)}</Text>
                  <Text style={[styles.cell, { width: "20%" }]}>{safeText(Array.isArray(supplier?.items) ? supplier.items.length : 0)}</Text>
                  <Text style={[styles.cell, styles.cellLast, { width: "45%" }]}>{formatCurrency(supplier?.totalAmount)}</Text>
                </View>
              ))
            )}
          </View>
        </View>
      </Page>
    </Document>
  );
}
