export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:3000/api";

export const USER_ROLES = {
  REQUESTING_OFFICER: "REQUESTING_OFFICER",
  DIRECTOR_ICT: "DIRECTOR_ICT",
  MAINTENANCE_ENGINEER: "MAINTENANCE_ENGINEER",
  DEAN: "DEAN",
  REGISTRAR: "REGISTRAR",
  BURSAR: "BURSAR",
  VICE_CHANCELLOR: "VICE_CHANCELLOR",
  SUPPLY_BRANCH: "SUPPLY_BRANCH",
  SUBJECT_CLERK: "SUBJECT_CLERK",
} as const;

export const PROCUREMENT_METHODS = [
  "SQ",
  "HQ",
  "ICB",
  "LIB",
  "LNB",
  "NCB",
  "NATIONAL_SHOPPING",
];
export const FUNDING_SOURCES = ["MPP", "SELF_FUND", "SPECIAL_FUND"];
export const ITEM_TYPES = ["IT", "NON_IT"];
