export const USER_ROLES = {
  ADMIN: "ADMIN",
  REQUESTING_OFFICER: "REQUESTING_OFFICER",
  DIRECTOR_ICT: "DIRECTOR_ICT",
  MAINTENANCE_ENGINEER: "MAINTENANCE_ENGINEER",
  SPECIFICATION_CHECKER: "SPECIFICATION_CHECKER",
  DEAN: "DEAN",
  REGISTRAR: "REGISTRAR",
  BURSAR: "BURSAR",
  VICE_CHANCELLOR: "VICE_CHANCELLOR",
  SUPPLY_BRANCH: "SUPPLY_BRANCH",
  SUBJECT_CLERK: "SUBJECT_CLERK",
  TEC_MEMBER: "TEC_MEMBER",
  MINOR_COMMITTEE: "MINOR_COMMITTEE",
  MAJOR_COMMITTEE: "MAJOR_COMMITTEE",
  FINANCE_OFFICER: "FINANCE_OFFICER",
};

export const REQUEST_STATUS = {
  SUBMITTED: "SUBMITTED",
  SPEC_REVIEW_PENDING: "SPEC_REVIEW_PENDING",
  SPEC_RETURNED_TO_REQUESTER: "SPEC_RETURNED_TO_REQUESTER",
  SPEC_REWORK_REQUESTED: "SPEC_REWORK_REQUESTED",
  SPEC_CONFIRMED_BY_REQUESTER: "SPEC_CONFIRMED_BY_REQUESTER",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CLARIFICATION_REQUESTED: "CLARIFICATION_REQUESTED",
  PROCUREMENT_STARTED: "PROCUREMENT_STARTED",
};

export const FUNDING_SOURCES = ["MPP", "SELF_FUND", "SPECIAL_FUND"];
export const ITEM_TYPES = ["IT", "NON_IT"];
export const FACULTY_UNITS = ["FAS", "FOT", "FBSF", "FOM", "FAPM", "FLFN"];
export const SERVICE_UNITS = ["ENGLISH_UNIT", "ICT_CENTER"];
export const REQUEST_UNITS = [...FACULTY_UNITS, ...SERVICE_UNITS];

export const getApprovalRoleForUnit = (unit) =>
  FACULTY_UNITS.includes(unit) ? USER_ROLES.DEAN : USER_ROLES.VICE_CHANCELLOR;

export const PROCUREMENT_METHODS = [
  "SQ",
  "HQ",
  "ICB",
  "LIB",
  "LNB",
  "NCB",
  "NATIONAL_SHOPPING",
];

export const APPROVER_ROLES = [
  USER_ROLES.DEAN,
  USER_ROLES.REGISTRAR,
  USER_ROLES.BURSAR,
  USER_ROLES.VICE_CHANCELLOR,
];

export const JOB_STATUS = {
  JOB_CREATED: "JOB_CREATED",
  CLERK_ASSIGNED: "CLERK_ASSIGNED",
  METHOD_SELECTED: "METHOD_SELECTED",
  CATEGORY_SELECTED: "CATEGORY_SELECTED",
  PENDING_TEC_DECISION: "PENDING_TEC_DECISION",
  TEC_DECISION_ENTERED: "TEC_DECISION_ENTERED",
  PENDING_MINOR_COMMITTEE_APPROVAL: "PENDING_MINOR_COMMITTEE_APPROVAL",
  PENDING_MAJOR_COMMITTEE_APPROVAL: "PENDING_MAJOR_COMMITTEE_APPROVAL",
  COMMITTEE_APPROVED: "COMMITTEE_APPROVED",
  COMMITTEE_REJECTED: "COMMITTEE_REJECTED",
  COMMITTEE_CLARIFICATION_REQUESTED: "COMMITTEE_CLARIFICATION_REQUESTED",
  COMMITTEE_AMENDMENT_REQUESTED: "COMMITTEE_AMENDMENT_REQUESTED",
  PURCHASE_ORDER_GENERATED: "PURCHASE_ORDER_GENERATED",
  DELIVERED: "DELIVERED",
  ACCEPTED: "ACCEPTED",
  PAYMENT_VOUCHER_GENERATED: "PAYMENT_VOUCHER_GENERATED",
};

export const TEC_DECISION_STATUS = [
  "RECOMMENDED",
  "REJECTED",
  "RECALL",
  "CALL_SAMPLE",
  "NOT_QUOTED",
];

export const COMMITTEE_TYPE = {
  MINOR: "MINOR",
  MAJOR: "MAJOR",
};

export const COMMITTEE_DECISION = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CLARIFICATION_REQUESTED: "CLARIFICATION_REQUESTED",
  RECOMMEND_AMENDMENT: "RECOMMEND_AMENDMENT",
};
