export const USER_ROLES = {
  REQUESTING_OFFICER: "REQUESTING_OFFICER",
  DIRECTOR_ICT: "DIRECTOR_ICT",
  MAINTENANCE_ENGINEER: "MAINTENANCE_ENGINEER",
  DEAN: "DEAN",
  REGISTRAR: "REGISTRAR",
  BURSAR: "BURSAR",
  VICE_CHANCELLOR: "VICE_CHANCELLOR",
  SUPPLY_BRANCH: "SUPPLY_BRANCH",
  SUBJECT_CLERK: "SUBJECT_CLERK",
};

export const REQUEST_STATUS = {
  SUBMITTED: "SUBMITTED",
  SPEC_REVIEW_PENDING: "SPEC_REVIEW_PENDING",
  SPEC_RETURNED_TO_REQUESTER: "SPEC_RETURNED_TO_REQUESTER",
  SPEC_REWORK_REQUESTED: "SPEC_REWORK_REQUESTED",
  SPEC_CONFIRMED_BY_REQUESTER: "SPEC_CONFIRMED_BY_REQUESTER",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CLARIFICATION_REQUESTED: "CLARIFICATION_REQUESTED",
  PROCUREMENT_STARTED: "PROCUREMENT_STARTED",
};

export const FUNDING_SOURCES = ["MPP", "SELF_FUND", "SPECIAL_FUND"];
export const ITEM_TYPES = ["IT", "NON_IT"];
export const PROCUREMENT_METHODS = [
  "SQ",
  "HQ",
  "ICB",
  "LIB",
  "LNB",
  "NCB",
  "NATIONAL_SHOPPING",
];

export const APPROVER_ROLES = [
  USER_ROLES.DEAN,
  USER_ROLES.REGISTRAR,
  USER_ROLES.BURSAR,
  USER_ROLES.VICE_CHANCELLOR,
];
